server {
    listen 80; # Nginx ascolta sulla porta 80
    server_name localhost;

    # Configurazione per la root dell'applicazione
    location / {
        root   /usr/share/nginx/html; # Dove Nginx trova i file statici
        index  index.html index.htm;  # File predefiniti da servire

        # Questa direttiva è FONDAMENTALE per le Single Page Applications (SPA).
        # Se un percorso non corrisponde a un file o directory esistente,
        # Nginx servirà comunque 'index.html'. Questo permette al router di Vue.js
        # (o qualsiasi altro router frontend) di gestire la navigazione lato client.
        try_files $uri $uri/ /index.html;
    }

    # Gestione delle pagine di errore
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
