openapi: 3.0.0


info: 
  title: Wasa Text
  description: |
    Questa API contiene le regole per
    far si che tutto funzioni al meglio
  version: 0.0.1
  
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        userId:
          type: string
          readOnly: true
        photo:
          type: string
          format: uri
          description: "URL to the user's or group's profile photo"
          example: "https://example.com/photos/group-photo.jpg"
    
    Chat:
      type: object
      properties:
        chatId:
          type: string
        title:
          type: string
          description: "Username or group name"
        photo:
          type: string
          format: uri
          description: "URL to the user's or group's profile photo"
          example: "https://example.com/photos/group-photo.jpg"
        isGroup:
          type: boolean
          description: "Indicates if the conversation is a group chat or one-on-one chat"
          example: false
        participants:
          type: array
          items:
            type: string
        lastMessage:
          $ref: "#/components/schemas/Message"
    
    Message:
      type: object
      properties: 
        messageId:
          type: string
        senderId: 
          type: string
        content:
          type: string
        photoUrl:
          type: string
          format: uri
          description: "URL to the photo (if the message is a photo message)"
          example: "https://example.com/photos/message-photo.jpg"
        timestamp:
          type: string
          format: date-time
          example: "2024-11-02T16:26:24Z"
        isForwarded:
          type: boolean
          default: false
  
  parameters:
    ChatId:
      schema:
        type: string
      required: true
      in: path
      name: ChatId
    
    MsgId:
      schema:
        type: string
      required: true
      in: path
      name: MsgId
    
    UserId:
      schema:
        type: string
      required: true
      in: path
      name: UserId


paths:
  /login:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "user123"
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
  
  /username:
    put: # Usiamo put per aggiornare le informazioni
      tags: ["Username"]
      summary: Setting username
      description: |-
        Allows an user to set their username
      operationId: updateUsername
      requestBody: 
        description: Username details
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
                  example: "user123"
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '200':
          description: Username change action successful
          content: 
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Username updated successfully"
        '400':
          description: Invalid username format or other errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid username format"

  /users:
    get:
      tags: [Users]
      summary: List of app users 
      description: "Allows a user to get a list of app users"
      operationId: listOfUsers
      responses:
        '200':
          description: List of app users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request"

  /conversations:
    get:
      tags: [My conversations]
      summary: Get the user's conversation history
      description: "Allows a user to get a list of his conversations"
      operationId: getMyConversations
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: "#/components/schemas/Chat"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request"
  
  /conversations/{ChatId}:
    get:
      tags: [Conversation]
      summary: Get the details of a conversation
      description: |-
        Allows a user to get the conversation details
      operationId: getConversation
      parameters:
        - $ref: "#/components/parameters/ChatId"
      responses:
        '200':
          description : details of conversation required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request"
  
  /conversations/{ChatId}/messages:
    post:
      tags: [Send message]
      summary: Allows a user to send a message
      description: |-
        gives the user the possibility to send a message
      operationId: sendMessage
      parameters:
        - $ref: "#/components/parameters/ChatId"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      
      responses:
        '201':
          description: message sent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request"
        
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "User not authorized to send a message in this conversation"
        
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Conversation with ID 'Chat8732' not found"

  /conversations/{ChatId}/messages/{MsgId}/forward:
    post:
      tags: [Forward]
      summary: Allows a user to forward a message
      description: gives the user the possibility to forward a message
      operationId: forwardMessage
      parameters:
        - $ref: "#/components/parameters/ChatId" #ID of the conversation containing the original message
        - $ref: "#/components/parameters/MsgId"  #ID of the original message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                targetChatId:
                  type: string
                  example: "Chat8732"
                targetUserId:
                  type: string
                  example: "User1234"
              oneOf:
                - required: ["targetChatId"]
                - required: ["targetUserId"]
      
      responses:
        '201':
          description: message forwarded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    $ref: "#/components/schemas/Message"
                  isForwarded:
                    type: boolean
                    default: true
        
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request parameters."
        
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "User not authorized to forward a message in this conversation."
        
        '404':
          description: Conversation or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Conversation or user not found."

  /conversations/{ChatId}/messages/{MsgId}/reaction:
    post:
      tags: [Reaction]
      summary: Allows a user to send a reaction to a message
      description: "gives the user the possibility to react a message with emoji "
      operationId: commentMessage
      parameters:
        - $ref: "#/components/parameters/ChatId" #ID of the conversation containing the message
        - $ref: "#/components/parameters/MsgId"  #ID of the original message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emoji:
                  type: string
                  description: "A single emoji character used as a reaction"
                  maxLength: 2
      responses:
        '200':
          description: Reaction added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Reaction added successfully"
                  reaction:
                    type: object
                    properties:
                      emoji:
                        type: string
                      userId:
                        type: string
        
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid emoji format"
        
        '404':
          description: Message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Message with Id: 8732 not found."
    
    delete:
      tags: [Reaction]
      summary: Allows a user to remove a reaction to a message
      description: "Allows a user to remove a previously added emoji reaction from a message."
      operationId: unCommentMessage
      parameters:
        - $ref: "#/components/parameters/ChatId" #ID of the conversation containing the message
        - $ref: "#/components/parameters/MsgId"  #ID of the original message
        - name: "Emoji"
          in: query
          required: true
          description: "The emoji to remove as a reaction from the message"
          schema:
            type: string
            maxLength: 2
      responses:
        '200':
          description: Reaction removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Reaction removed successfully"
        
        '400':
          description: Invalid input or missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid emoji or message ID"
        
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not authorized to remove reaction"
        
        '404':
          description: Message or reaction not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Reaction not found on the message"
  
  
  
  
  
  
  
  