openapi: 3.0.0


info: 
  title: Wasa Text
  description: |
    Questa API contiene le regole per
    far si che tutto funzioni al meglio
  version: 0.0.1
  
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        userId:
          type: string
          readOnly: true
        photo:
          
          description: "Base64-encoded image data"
    
    Chat:
      type: object
      properties:
        chatId:
          type: string
          example: "Chat8732"
        title:
          type: string
          description: "Username or group name"
        photo:
          type: string
          format: uri
          description: "URL to the user's or group's profile photo"
          example: "https://example.com/photos/group-photo.jpg"
        isGroup:
          type: boolean
          description: "Indicates if the conversation is a group chat or one-on-one chat"
          example: false
        participants:
          type: array
          items:
            type: string
        lastMessage:
          $ref: '#/components/schemas/Message'
    
    Message:
      type: object
      items:
        properties: 
          messageId:
            type: string
          senderId: 
            type: string
          content:
            type: string
          photoUrl:
            type: string
            format: uri
            description: "URL to the photo (if the message is a photo message)"
            example: "https://example.com/photos/message-photo.jpg"
          timestamp:
            type: string
            format: date-time
            example: "2024-11-02T16:26:24Z"
            
    

          
paths:
  /login:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "user123"
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
  
  /username:
    put: # Usiamo put per aggiornare le informazioni
      tags: ["Set Username"]
      summary: Setting username
      description: |-
        Allows an user to set their username
      operationId: updateUsername
      requestBody: 
        description: Username details
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
                  example: "user123"
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '200':
          description: Username change action successful
          content: 
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Username updated successfully"
        '400':
          description: Invalid username format or other errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid username format"

  /conversations:
    get:
      tags: [My conversations]
      summary: Get the user's conversation history
      description: |-
        Allows a user to get a list of his conversations
      operationId: getMyConversations
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: "#/components/schemas/Chat"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request"
  
  /conversations/{conversationId}:
    get:
      tags: [Conversation]
      summary: Get the details of a conversation
      description: |-
        Allows a user to get the conversation details
      operationId: getConversation
      parameters:
      - name: conversationId
        in: path
        required: true
        description: A unique conversation ID
        schema:
          type: string
          example: "Chat8732"
      responses:
        '200':
          description : details of conversation required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
        '400':
          description: Invalid request parameters
  
  /conversations/{conversationId}/sendMessage:
    post:
      tags: [Send message]
      summary: Allows a user to send a message
      description: |-
        
      operationId: sendMessage
      parameters:
        - name: conversationId
          in: path
          required: true
          description: The unique ID of the conversation
          schema:
            type: string
            example: "Chat8732"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      
      responses:
        '201':
          description: message sent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Invalid request"
          
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "User not authorized to send a message in this conversation"  
        
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: "Conversation with ID 'Chat8732' not found"
  
  
  
  
  
  
  
  
  